
server:
  port : ${PORT:7080}

#management:
#   security:
#      enabled: false
#   endpoint:
#      health:
#        show-details: always

spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: p55
    
  jpa:  
    defer-datasource-initialization: true