
server:
  port : ${PORT:7080}

#management:
#   security:
#      enabled: false
#   endpoint:
#      health:
#        show-details: always

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:/Users/antonio.ruiz/Documents/OpenApi/h2
    driverClassName: org.h2.Driver
    username: sa
    password: password
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
h2:
  console:
    enabled: true