
server:
  port : ${PORT:7080}
debug: true
spring:
  datasource:
    url: jdbc:h2:mem:mydb_anybal
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

#management:
#   security:
#      enabled: false
#   endpoint:
#      health:
#        show-details: always