---TABLES creation

DROP TABLE if exists account; 
DROP TABLE if exists customer; 
DROP TABLE if exists user_data; 

CREATE TABLE account (
       account_number bigint generated by default as identity,
        account_type varchar(255),
        balance float,
        customer_id bigint,
        overdraft_allowed boolean,
        overdraft_amount float,
        primary key (account_number)
    );

CREATE TABLE customer (
       customer_number bigint generated by default as identity,
        active boolean,
        at_date boolean,
        customer_type varchar(255),
        primary key (customer_number)
    );

CREATE TABLE user_data (
       user_id bigint generated by default as identity,
        email varchar(255),
        full_name varchar(255) not null,
        password varchar(255) not null,
        status integer,
        user_name varchar(255) not null,
        primary key (user_id)
    );

--- ACCOUNT TABLE     
ALTER TABLE account ADD CONSTRAINT fk_customer foreign key (customer_id) references customer;

ALTER TABLE account ALTER COLUMN account_number RESTART WITH 1000000001;

INSERT INTO account (account_type, balance, overdraft_allowed, overdraft_amount) VALUES('SAVING', 2550.25, 1, 1050.36);

--- CUSTOMER TABLE 
ALTER TABLE customer ALTER COLUMN customer_number RESTART WITH 10001;

INSERT INTO user_data (email, full_name, password, status, user_name) VALUES ('al@gmail.com','Aline Perez','w#CDfr546#@',1,'alineG1245');